### PR TITLE
feat: upgrade chart to v1.5.2

### PR DESCRIPTION
**Pull request by hbollon**
## Description of the changes

Upgrade Longhorn chart to v1.5.2. 
This upgrade is required to be able to add recurring jobs to automate filesystem trim. 
Upgrading from v1.4.x to v1.5.x is straight forward and can be done in-place (cf. https://longhorn.io/docs/1.5.3/deploy/upgrade/longhorn-manager/ and tested on SKS cluster)

## Breaking change

- [x] No
- [ ] Yes (in the Helm chart(s)): _indicate the chart, version & release note link_
- [ ] Yes (in the module itself): _give an explanation of the breaking change_

## Tests executed on which distribution(s)

- [ ] KinD
- [ ] AKS (Azure)
- [ ] EKS (AWS)
- [ ] Scaleway
- [x] SKS (Exoscale)

### CODE REVIEW

**Comment by lentidas** [comment]
@hbollon I've had this upgrade on the pipeline for a while in the PR #12. While an upgrade in-place does work, there are some problems with the chart that prevent it from being deployed on a cluster bootstrap. I do not recall precisely what the problem was, but I remember they were expecting to fix it on the v1.6.0 of the chart. Do you mind if I test the new version on a bootstrap before merging this?

**Comment by lentidas** [comment]
This is the comment I made on the other PR about the issue, I'll need to restart my research about the issue to freshen up my memory... -> https://github.com/camptocamp/devops-stack-module-longhorn/pull/12#issuecomment-1695378469

**Comment by hbollon** [comment]
I can wait until v1.6.0
My cluster is currently deployed on the `pre-release/v3.1.0` branch where I merged my PRs to be able to keep working until the v3.1.0 (or v4 depending of the final changelog) is released :+1:

**Comment by hbollon** [comment]
Closed in favor of #12

**Pull request closed without merging**
